from .coreference_resolution import COREFERENCE_RESOLUTION_PROMPT
from .description_rephrasing import DESCRIPTION_REPHRASING_PROMPT
from .generation import (
    AGGREGATED_GENERATION_PROMPT,
    ATOMIC_GENERATION_PROMPT,
    ATOMIC_GENERATION_PROMPT_VARIANTS,
    ATOMIC_GENERATION_PROMPT_CHINESE_ONLY,
    ATOMIC_GENERATION_PROMPT_VARIANTS_CHINESE_ONLY,
    ATOMIC_ANSWER_PROMPT,
    ATOMIC_ANSWER_PROMPT_CHINESE_ONLY,
    ATOMIC_QUESTION_PROMPT,
    ATOMIC_QUESTION_PROMPT_CHINESE_ONLY,
    COT_GENERATION_PROMPT,
    HIERARCHICAL_GENERATION_PROMPT,
    MULTI_HOP_GENERATION_PROMPT,
)
from .kg import KG_EXTRACTION_PROMPT, KG_SUMMARIZATION_PROMPT, MMKG_EXTRACTION_PROMPT
from .question_generation import QUESTION_GENERATION_PROMPT
from .search_judgement import SEARCH_JUDGEMENT_PROMPT
from .statement_judgement import STATEMENT_JUDGEMENT_PROMPT
