from .aggregated_generation import AGGREGATED_GENERATION_PROMPT
from .atomic_generation import (
    ATOMIC_GENERATION_PROMPT,
    ATOMIC_GENERATION_PROMPT_VARIANTS,
    ATOMIC_GENERATION_PROMPT_CHINESE_ONLY,
    ATOMIC_GENERATION_PROMPT_VARIANTS_CHINESE_ONLY,
    ATOMIC_QUESTION_PROMPT,
    ATOMIC_QUESTION_PROMPT_CHINESE_ONLY,
    ATOMIC_ANSWER_PROMPT,
    ATOMIC_ANSWER_PROMPT_CHINESE_ONLY,
)
from .cot_generation import COT_GENERATION_PROMPT
from .hierarchical_generation import HIERARCHICAL_GENERATION_PROMPT
from .multi_hop_generation import MULTI_HOP_GENERATION_PROMPT
